### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Soham52** [KxmischesDomi/MoreBannerFeatures#1]
After installing the mod on the server the server crashed on startup.
the log: 
[latest.log](https://github.com/KxmischesDomi/MoreBannerFeatures/files/6988382/latest.log)

**Comment by KxmischesDomi** [comment]
Thanks for your report, I'm looking over it now!

**Comment by KxmischesDomi** [comment]
Could you try [this version](https://workupload.com/file/WrtCwxFJKhG) of the mod?

**Comment by Soham52** [comment]
It worked, thanks :) but i did notice that piglin brutes were not wearing banners, maybe a bug

**Comment by KxmischesDomi** [comment]
Will look at that, thanks for telling me

**Comment by KxmischesDomi** [comment]
Have you spawned the Piglins with Spawn Eggs? The Piglins only have Banners when naturally spawned in a Bastion.

**Comment by Soham52** [comment]
I saw them at a bastion

**Comment by Soham52** [comment]
Oh, now i get it, so i did of experimenting and found out that the piglins that i saw had already spawned before i installed the mod thats why they did not have any banners, the newer ones did have banners on them, sorry for the false report

**Comment by KxmischesDomi** [comment]
No Problem, I'm gonna close the issue then! :)
