### ISSUE TITLE
Compatibility with Biome Makeover Tapestrys

### ISSUE THREAD

**Issue by Lukebb04** [KxmischesDomi/MoreBannerFeatures#10]
[Biome Makeover](https://www.curseforge.com/minecraft/mc-mods/biome-makeover)

**Comment by DomiIRL** [comment]
What do you mean with compatability? Does it crash or is there any specific block or banner?

**Comment by Lukebb04** [comment]
they add a new banners called Tapestrys

**Comment by DomiIRL** [comment]
Don't think this will work on any way possible.
