### ISSUE TITLE
Bug: there is no dark UI for horses and donkeys and mules

### ISSUE THREAD

**Issue by EGOIST1372** [KxmischesDomi/MoreBannerFeatures#14]
there is no dark UI for horses and donkeys and mules and it's weird
![image](https://user-images.githubusercontent.com/86555131/155838670-af0b23dc-8d1d-41d1-bc24-ab60d94700fb.png)

**Comment by DomiIRL** [comment]
You have to update the texture yourself.
How to do that is described here: https://www.curseforge.com/minecraft/mc-mods/more-banner-features/screenshots

**Comment by EGOIST1372** [comment]
for those who want the mod with dark UI
![image](https://user-images.githubusercontent.com/86555131/155844822-985b6fe3-6fd1-4fc3-8ccc-1752fd9d6b10.png)

here is the link(unzip):
[morebannerfeatures-1.1.3-1.18_darkui.zip](https://github.com/KxmischesDomi/MoreBannerFeatures/files/8146674/morebannerfeatures-1.1.3-1.18_darkui.zip)
