### ISSUE TITLE
BYG Boat Support for Banner Features

### ISSUE THREAD

**Issue by ardissaps** [KxmischesDomi/MoreBannerFeatures#19]
Would you please make compatibility with these mods? Thank you very much (1.18.2)

[Oh BYG](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) :
![image](https://user-images.githubusercontent.com/82106625/178454214-51e743eb-1620-4529-9983-0ccde81ae70f.png)

[Charm](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) :
![image](https://user-images.githubusercontent.com/82106625/178454724-226a347f-0f61-4eee-a1fa-b100856589a6.png)

Also for Boat Container :
https://github.com/KxmischesDomi/BoatContainer/issues/28

**Comment by DomiIRL** [comment]
Duplicate of https://github.com/KxmischesDomi/MoreBannerFeatures/issues/18

**Comment by ardissaps** [comment]
Sorry the duplicate was caused by my slowass internet. :p
