### ISSUE TITLE
banner dupe multiplayer 1.19.2

### ISSUE THREAD

**Issue by WarlordWossman** [KxmischesDomi/MoreBannerFeatures#20]
1.19.2 most recent version of the mod:
If you mount a llama and shift click a banner it goes into the player inventory but dupes more of them.
Tested on a multiplayer server.

**Comment by DomiIRL** [comment]
1. Does this also occur to you on singleplayer?
2. Could this be related to a mod conflict? I wasn't able to reproduce it in singleplayer.

**Comment by WarlordWossman** [comment]
1. Doesn't happen in singleplayer
2. Only thing I could think of is item scroller but it also happened when I tried shift clicking in and out banners into a trader llama inventory slot (the banner one added by the mod). 
For reference I really don't use many mods and this is the only one that should touch banners.

**Comment by DomiIRL** [comment]
Could you try your setup without the item scrolle mod and report back to me? Would have to know if thats an issue that only happens for you.
Gonna look tomorrow if I can reproduce it myself
