### ISSUE TITLE
Able to shear Pigs, Striders, Boats & Villagers without banners

### ISSUE THREAD

**Issue by SplendidAlakey** [KxmischesDomi/MoreBannerFeatures#24]
**MC** 1.19.2
**FAPI** 0.67.1
**MoreBannerFeatures** 1.1.3

It is possible to use shears on Pigs, Striders, Boats & Villagers, that don't have banners. It wastes durability on shears and does nothing. The mod should check, whether an entity has a banner, before allowing to use shears on it.

**Comment by DomiIRL** [comment]
It should... gonna check that as soon as I have my internet connection back at home

**Comment by SplendidAlakey** [comment]
Must've been a problem on my side, as I'm no longer able to reproduce this.
