### ISSUE TITLE
[Feature Request] Cape banners

### ISSUE THREAD

**Issue by OakBricks** [KxmischesDomi/MoreBannerFeatures#3]
title

this would allow players to use banners as cheap disposable capes in-game that could only be used on that server/world, i think this would work best with a custom armor slot or something like curious or trinkets

**Comment by KxmischesDomi** [comment]
Infact I already tried that but I wasn't able to figure out how to do it sadly. The Banner Textures are not made with a List of BannerPatterns like everything else related to banners but with a redirection to a specific path like a texture or smth. 
I could try to make my own Renderer and if that works I will definitely add it!

**Comment by KxmischesDomi** [comment]
Implemented with this update: https://www.curseforge.com/minecraft/mc-mods/more-banner-features/files/3442160
