### ISSUE TITLE
Crash when Artifality invisibility cloak present 

### ISSUE THREAD

**Issue by Shads404** [KxmischesDomi/MoreBannerFeatures#4]
Bug present in 1.04/1.05.  reverting to 1.03 resolves issue.
Tested in BetterMC 1.17 pack

Fresh world, creative add Inivisbility cloak from artifality and instant crash occurs.
[crash-2021-09-01_03.51.01-client.txt](https://github.com/KxmischesDomi/MoreBannerFeatures/files/7090587/crash-2021-09-01_03.51.01-client.txt)

**Comment by KxmischesDomi** [comment]
Found the problem and I will update as quickly as I can!

**Comment by KxmischesDomi** [comment]
Should be fixed with: https://www.curseforge.com/minecraft/mc-mods/more-banner-features/files/3447090
