### ISSUE TITLE
[Crash] Elytra Trinket

### ISSUE THREAD

**Issue by SylisMC** [KxmischesDomi/MoreBannerFeatures#5]
[crash-2021-09-01_19.20.13-client.txt](https://github.com/KxmischesDomi/MoreBannerFeatures/files/7095018/crash-2021-09-01_19.20.13-client.txt)

https://www.curseforge.com/minecraft/mc-mods/elytra-trinket-fabric

Game crashes whenever you try to place an elytra in the cape slot, im not sure whos mod is "at fault" but the cape feature was only recently added, so im assuming its something within morebanners

**Comment by KxmischesDomi** [comment]
I found the problem and I will update the mod as quickly as I can ^^

**Comment by KxmischesDomi** [comment]
Should be fixed with: https://www.curseforge.com/minecraft/mc-mods/more-banner-features/files/3447090

**Comment by SylisMC** [comment]
You're awesome, thanks
