### ISSUE TITLE
Data trackers are registered on the wrong classes, causing compatibility issues

### ISSUE THREAD

**Issue by Fourmisain** [KxmischesDomi/MoreBannerFeatures#8]
I noticed an incompatibility with Earth2Java where Muddy Pigs cannot be spawned, logging "duplicate id" errors.

This seems to be caused by data trackers of this mod not being registered properly, relevant parts are here:
https://github.com/KxmischesDomi/MoreBannerFeatures/blob/af68487ceb9317479acc1c1258eb73a42f5049da/src/main/java/de/kxmischesdomi/morebannerfeatures/mixin/pig/PigEntityMixin.java#L144
https://github.com/KxmischesDomi/MoreBannerFeatures/blob/af68487ceb9317479acc1c1258eb73a42f5049da/src/main/java/de/kxmischesdomi/morebannerfeatures/mixin/boat/BoatEntityMixin.java#L129
https://github.com/KxmischesDomi/MoreBannerFeatures/blob/af68487ceb9317479acc1c1258eb73a42f5049da/src/main/java/de/kxmischesdomi/morebannerfeatures/mixin/strider/StriderEntityMixin.java#L119

Correcting the classes seems to fix the issue.

**Comment by KxmischesDomi** [comment]
Thanks for reaching out, I'm gonna fix that tomorrow and upload a new verison on Curseforge ^^

**Comment by KxmischesDomi** [comment]
Should be fixed with https://github.com/KxmischesDomi/MoreBannerFeatures/commit/163b9ec1081d0b12e6c0ef16bf47ce3177e07441.
Guess I'm gonna update it today, not tomorrow

**Comment by KxmischesDomi** [comment]
Fixed and uploaded: https://www.curseforge.com/minecraft/mc-mods/more-banner-features/files/3453480
