### ISSUE TITLE
Compatibility Issues with Physics Pro version

### ISSUE THREAD

**Issue by Adeliwyr** [KxmischesDomi/MoreBannerFeatures#9]
The game cannot launch with the Pro version of Physics which adds physics to Banner & Cape

If a fix could be found it would be incredible or if it is impossible it should be added in the Incompatibilities section :p

**Comment by KxmischesDomi** [comment]
Sorry for the late answer, this problem has also reported to me another time lately and I managed to fix it.
I'm going to upload a fix on curseforge soon
